//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDFINALPROGRA1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_relojes
    {
        public int IdRelojes { get; set; }
        public string Nombre { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Mecanismo { get; set; }
        public string Genero { get; set; }
        public int Precio { get; set; }
        public string Correa { get; set; }
        public string Color { get; set; }
        public string Fecha { get; set; }
    }
}
